# Generated by Django 3.2.16 on 2022-11-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(max_length=250)),
                ('pimg', models.ImageField(upload_to='pis')),
                ('tdesc', models.TextField()),
            ],
        ),
    ]
